### ISSUE TITLE
MSG file size doubles after converting from EML

### ISSUE THREAD

**Issue by priuser** [Sicos1977/MsgKit#64] opened 2020-02-05 02:59 UTC
creating EML files using mimekit and then using msgkit to convert to .MSG. The file size doubles in the newly created MSG file.

**Comment by Sicos1977** [comment] 2020-02-05 17:43
Does you eml file only have a body or does it also have attachments? MSGKit stores the body as unicode so this can double the message size since this is a 2 byte charset

**Comment by priuser** [comment] 2020-02-05 17:50
> Does you eml file only have a body or does it also have attachments? MSGKit stores the body as unicode so this can double the message size since this is a 2 byte charset

Hey, Thank you for getting back.

Yes it includes attachments also. Attached both eml and msg files.

What’s the solution for this ?

Thank you!

**Comment by Sicos1977** [comment] 2020-02-05 17:51
Can you send me the file so that I can see what MSGKit is doing. If so then please send it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment] 2020-02-05 18:27
I confirmed its a bug, the conversion code was writing twice to the same memorystream doubling all attachments in size. It is fixed in this commit d4b73a3dd217188539430302993a3b51c23ac19c

**Closed by Sicos1977** 2020-02-05 18:27 UTC

**Comment by Sicos1977** [comment] 2020-02-05 18:31
I just uploaded a new package to nuget. It should be available soon.

**Comment by priuser** [comment] 2020-02-05 18:33
Perfect, Thank you much! Let me pull the latest in 3 hours and check it out!
Appreciate all your help!

**Comment by Sicos1977** [comment] 2020-02-05 18:36
No problems ... if you make a mess then you have to clean it up :-)

**Comment by priuser** [comment] 2020-02-06 17:15
Thank you the doubling issue is resolved!!!
